merge_mode: replace
jobs:
  include:
    - os: windows
      language: bash
    - os: linux
      dist: bionic
      language: generic
      env:
      - MSSQL_SA_PASSWORD="YourStrong!Passw0rd"
      - ACCEPT_EULA=Y
      - MSSQL_PID='evaluation'
      services:
      - postgresql
      - mysql
      addons:
        apt:
          sources:
            - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main'
              key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
            - sourceline: 'deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main'

addons:

services:
env:
cache:
  directories:
  - $HOME/.local/share/NuGet/
  - $HOME/.nuget
  - $HOME/.m2
  - $HOME/rdmp-cli

install:
- export RDVERSION=$(fgrep Version SharedAssemblyInfo.cs|cut -d'"' -f2|head -n1)
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]
  then
    sudo apt-get install -y --no-install-recommends mssql-tools mssql-server libc6-dev libgdiplus dotnet-runtime-2.2 dotnet-sdk-3.1
    sudo /opt/mssql/bin/mssql-conf -n setup accept-eula
    if [ ! -x $HOME/rdmp-cli/rdmp ] || ! fgrep -q 4.1.0 $HOME/rdmp-cli/rdmp.dll
    then
      rm -rf $HOME/rdmp-cli
      wget https://github.com/HicServices/RDMP/releases/download/v4.1.0/rdmp-cli-linux-x64.zip
      # RDMP is still being packaged using a ZIP tool with a bug Microsoft fixed in .Net 4.6.1; excluding Chinese language support file and keyword help avoids unzip being affected by the bug: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator?redirectedfrom=MSDN
      unzip -d $HOME/rdmp-cli rdmp-cli-linux-x64.zip -x "Curation*" "zh-*"
      chmod +x $HOME/rdmp-cli/rdmp
    fi
  $HOME/rdmp-cli/rdmp install localhost TEST_ -u sa -p 'YourStrong!Passw0rd'
  fi
- |
  if [ "$TRAVIS_OS_NAME" = "windows" ]
  then
    if [ ! -x $HOME/rdmp-cli/rdmp.exe ] || ! fgrep -q 4.1.0 $HOME/rdmp-cli/rdmp.dll
    then
      rm -rf $HOME/rdmp-cli
      wget https://github.com/HicServices/RDMP/releases/download/v4.1.0/rdmp-cli-win-x64.zip
      7z x rdmp-cli-win-x64.zip -o$HOME/rdmp-cli
    fi
    echo "ServerName: localhost" > Rdmp.Dicom.Tests/TestDatabases.txt
    echo "Prefix: TEST_" >> Rdmp.Dicom.Tests/TestDatabases.txt
    choco install sql-server-2017
    choco install dotnetcore --version=2.2.2
    choco install dotnetcore-sdk
    choco install nuget.commandline
    $HOME/rdmp-cli/rdmp.exe install localhost TEST_
  fi

script:
- dotnet build "./Rdmp.Dicom/Rdmp.Dicom.csproj"
- dotnet build "./Rdmp.Dicom.Tests/Rdmp.Dicom.Tests.csproj"
- dotnet test "./Rdmp.Dicom.Tests/Rdmp.Dicom.Tests.csproj"
- |
  if [ "$TRAVIS_OS_NAME" = "windows" ]
  then
    cd Plugin/net461
    dotnet publish --runtime win-x64 -c Release --self-contained false
    cd ../netcoreapp2.2
    dotnet publish --runtime win-x64 -c Release --self-contained false
    dotnet publish --runtime linux-x64 -c Release --self-contained false
    cd ../..
    nuget pack ./Rdmp.Dicom.nuspec -Properties Configuration=Release -IncludeReferencedProjects -Symbols -Version ${RDVERSION}
    nuget pack ./Rdmp.Dicom.Library.nuspec -Properties Configuration=Release -IncludeReferencedProjects -Symbols -Version ${RDVERSION}
    ls -lh *.nupkg
    $HOME/rdmp-cli/rdmp.exe pack --file Rdmp.Dicom.${RDVERSION}.nupkg --servername localhost --cataloguedatabasename TEST_Catalogue --dataexportdatabasename TEST_DataExport
    $HOME/rdmp-cli/rdmp.exe cmd listsupportedcommands --servername localhost --cataloguedatabasename TEST_Catalogue --dataexportdatabasename TEST_DataExport
    $HOME/rdmp-cli/rdmp.exe cmd describecommand CreateNewImagingDatasetSuite --servername localhost --cataloguedatabasename TEST_Catalogue --dataexportdatabasename TEST_DataExport
    mkdir -p $HOME/dist
    mv Rdmp.Dicom.${RDVERSION}.nupkg $HOME/dist/
    cd
    
    if [ ! -z "$TRAVIS_TAG" ]
    then
      nuget push HIC.Rdmp.Dicom.${RDVERSION}.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $NUGET_KEY
    fi
  fi

deploy:
      provider: releases
      token:
        secure: lrduiWMD0cuQgmtlhSzmZRoLc3XPLOyJEBYQsCE6Mjrwa/ITtttaB9h1gPs88eZvtWKFlLv7IcW8wZIobS4ZVzzpXq/aY6R2AHWhwqg+RfgOlNscPM28tiagXEe1hf8ypQkaouZBmARXact11pq3Ce/Jc8XYC7++xVfhTNQrRRVOvJ86h1Sd2KAThorP2cLaCzPXuhhC7CD9O4c+VfmhwDbfuCmgzxuHx8+XqOcC4lKNhp03aS4fChxwfJagKPO1HYQ9QidXqR62Wo7mquTJ1STR3zwGhTA57QMEMER0Sj7f5VnyZJALSrr4mu8Ho1mPwXHMJMFwvXKCgD0l6mwVaIUPezbIUFmpo3rZR4MC+iH1dzMDP95c53ChCPTDXLdDI2nWTL+IIBWyaiTYUZX95hAAV8CrgBmOCA+s7J7+/8IgEgznhOGVnnF28B5JDDADsM0YReYrwDZ3RTN3wu6ZB1N0MaBKVAT7ghgCLdHyHESteoQhri+CNYnu9XAdTOZqWjYKV7kFcMGf8htzy0y9p/4u40DU8icXitrR4cIZVn1nIq5cu8uz84TraaBIAcOmRRcVBLBXSgxYmlWF8NrEZQxBPYsQOs+iA/AvZ2tYCtlqsFGgJi5zl1t2BHPqjoKZb5mhy95E71oA/JL4riUpLgser4PfFQccyTEG7tM5ExA=
      file_glob: true
      file: dist/*.nupkg
      skip_cleanup: true
      on:
        all_branches: true
        tags: true
